# use Ganache's forked mainnet mode as the default network
networks:
  default: ftm-main-fork

autofetch_sources: true

dependencies:
  - OpenZeppelin/openzeppelin-contracts@4.3.0

# path remapping to support OpenZepplin imports with NPM-style path
compiler:
  solc:
    version: 0.8.7
    optimizer:
      runs: 800
      details:
        yul: False
    remappings:
      - "@openzeppelin=OpenZeppelin/openzeppelin-contracts@4.3.0"
